name: Create Workflow Dispatch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: zabit82,
              repo: repo-test-2,
              workflow_id: 'blank.yml',
              ref: 'main',
            })
